name: "Update star list"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  build:
    name: "star list update"
    runs-on: ubuntu-latest
    steps:
      - name: "Use GitHub Actions"
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Make List
        run: |
          go run . > README.md
      - name: commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
