name: "Update by stargazed"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: "stargazed update"
    runs-on: ubuntu-latest
    steps:
      - name: "Use GitHub Actions"
        uses: actions/checkout@v2
      - name: "Use Node.js 12.x"
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: "Update Repo"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: "npx stargazed --username lemon-mint --token ${GITHUB_TOKEN} --repo stars --message 'chore: update stargazed' --sort"
